on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: Generate HTML From Roam
      uses: dvargas92495/generate-roam-site-action@v1.3.1
      with:
        roam_username: dvargas92495@gmail.com
        roam_password: ${{ secrets.ROAM_PASSWORD }}
        roam_graph: dvargas92495
